### PR TITLE
Python 3 fixes

### PR DESCRIPTION
**Pull request by ams**
See also comment by @eswenson1 in https://github.com/PDP-10/its/pull/1511#issuecomment-457955443

### CODE REVIEW

**Comment by ams** [comment]
@bictorv and @eswenson1 Here you go.

**Comment by ams** [comment]
@larsbrinkhoff Can you loosen/extend the permissions on the Chaosnet group?

**Comment by larsbrinkhoff** [comment]
I changed something from "Read only" to "Write".  Is it better now?

**Comment by ams** [comment]
Yes!

**Comment by eswenson1** [comment]
Although this runs now for me in python 3, it emits strings for hardware and operating system enclosed in d’xxx’. A simple edit of the output, of course, yields a usable file.

**Comment by ams** [comment]
Yeah, Python is annoying ... see pull request.  Should be fixed now.

**Comment by eswenson1** [comment]
Yup. Looks good. Thanks.

**Pull request merged**
